services:
  mdnsd:
    container_name: mdnsd
    environment:
      MDNSD_DOCKER_NETWORKS: 'traefik-proxy'
      MDNSD_HOST_INTERFACES: 'enp6s0'
    image: ghcr.io/shyndman/mdnsd
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
